# NumPy

## What is NumPy?

**NumPy** (Numerical Python) is an open-source Python library used for **fast numerical computing**.

It provides a powerful data structure called **ndarray (N-dimensional Array)**, which allows us to store and manipulate large amounts of numerical data efficiently.

NumPy is one of the most important libraries in the Python ecosystem and serves as the foundation for many other libraries such as:

- Pandas
- Matplotlib
- Seaborn
- Scikit-learn
- TensorFlow
- PyTorch

---

# Why Do We Need NumPy?

Python lists are flexible but become slow when working with large amounts of numerical data.

NumPy solves this problem by providing:

- Faster execution
- Lower memory usage
- Powerful mathematical operations
- Easy handling of multi-dimensional data

---

# Problems with Python Lists

Suppose we want to add two lists.

```python
a = [1, 2, 3]
b = [4, 5, 6]

result = []

for i in range(len(a)):
    result.append(a[i] + b[i])

print(result)
```

Output

```
[5, 7, 9]
```

This works, but writing loops repeatedly becomes slow and inefficient for large datasets.

---

# NumPy Solution

```python
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

print(a + b)
```

Output

```
[5 7 9]
```

No loop is required.

The code is shorter, cleaner, and much faster.

---

# Advantages of NumPy

✅ Faster than Python lists

✅ Uses less memory

✅ Easy mathematical calculations

✅ Supports multi-dimensional arrays

✅ Optimized for large datasets

✅ Provides hundreds of built-in mathematical functions

---

# Real-World Uses

NumPy is widely used in:

- Data Science
- Machine Learning
- Artificial Intelligence
- Deep Learning
- Data Analysis
- Scientific Computing
- Computer Vision
- Image Processing

---

# Why AI & ML Engineers Use NumPy

Machine Learning works with numbers.

For example:

- Student marks
- House prices
- Images
- Audio signals
- Videos
- Sensor data

All of this data must be stored and processed efficiently.

NumPy provides the speed and mathematical operations required for handling these large datasets.

---

# Example

Suppose we have marks of students.

```python
import numpy as np

marks = np.array([78, 85, 90, 66, 92])

print(marks.mean())
print(marks.max())
print(marks.min())
```

Output

```
82.2
92
66
```

NumPy performs these calculations using built-in optimized functions.

---

# Key Features

- High-performance N-dimensional arrays
- Fast mathematical operations
- Broadcasting
- Vectorization
- Matrix operations
- Linear algebra
- Random number generation
- Statistical functions

---

# Summary

NumPy is the foundation of Data Science and Machine Learning.

It allows developers to perform numerical computations efficiently using powerful arrays and optimized mathematical functions.

Learning NumPy is the first major step after mastering Python for anyone pursuing AI, Machine Learning, or Data Science.

---

### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

# Remember always if output of function show after runing it is not permnant  operation mean cannot change orignal object if output is not shown then operation is permanant and it change our orignal object

# Creating numpy array

In [461]:
import numpy as np  # 1d array called vector

a = np.array([1,2,3])

print(a)
type(a)

[1 2 3]


numpy.ndarray

In [462]:
# 2d and 3d array    2d array called matrix

d2 = np.array([[1,2,3,4],[1,2,3,4]])

print(d2)
type(d2)

[[1 2 3 4]
 [1 2 3 4]]


numpy.ndarray

In [539]:
d3 = np.array([[[1,2],[2,4]],[[3,4],[5,7]]]) #3d rray called tensor
d4 = np.array([[[1,13],[14,15]],[[16,16],[17,17]]])
print(d3,"\n") # 3d array



[[[1 2]
  [2 4]]

 [[3 4]
  [5 7]]] 



In [540]:
print(d4) # 3d array

[[[ 1 13]
  [14 15]]

 [[16 16]
  [17 17]]]


# Making numpy array of data type we want 
using dtype keyword

In [464]:
#dtype

np.array([1,2,3,4],dtype = float) #float type array  

array([1., 2., 3., 4.])

In [465]:
np.array([1,2,3,4],dtype = bool)   #bool type

array([ True,  True,  True,  True])

In [466]:
np.array([1,2,3,4],dtype = complex)  #complex type 

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

# Creating  array with arange work similar like range in pyton loops

when we make array using numpy array it alway in float data type

In [467]:
Comp = np.arange(1,11)
print(Comp)
gap = np.arange(1,11,3) # 3  coresponding gap between numbers
print(gap)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  4  7 10]


# Checking shape of np array



In [468]:
np.arange(1,11).reshape(5,2)  #reshape(5,2) is converting its shape into 5 rows 2 columns

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [469]:
np.arange(1,16).reshape(5,3) # reshaping np array into 5 rows nd 3 columns

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

# np.ones and np.zeros

np.ones create array in which all members are 1 and np.zeros create array in which all members are 0

In [470]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [471]:
np.ones((3,2),dtype= int) # making int array instead of float

array([[1, 1],
       [1, 1],
       [1, 1]])

In [472]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# np.random

In [473]:
np.random.random((1,9))

array([[0.14259467, 0.55776968, 0.99777724, 0.10631305, 0.75788687,
        0.13613329, 0.15026319, 0.72539381, 0.69854628]])

# np.linspace 

we provide  range in it  and its syntax is 

np.linspace(-10,10,10)  first 10 show lower range next 10 shows upper range 3rd 10  show number of items we need to gen

In [474]:
np.linspace(-10,10,10) 

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

# np.identity  Create identity matrix

In [475]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Array Attributes 

In [476]:
a1 = np.arange(10,dtype= np.int32)
a2 = np.arange(12, dtype = float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

print(a1,"\n")
print(a2,"\n")
print(a3,"\n")


[0 1 2 3 4 5 6 7 8 9] 

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]] 

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]] 



# 1st attribute ndim  use to check dimension of array

- ndim

In [477]:
print(a3.ndim,"\n")

print(a1.ndim,"\n")
print(a2.ndim,"\n")

3 

1 

2 



# 2nd attribute shape use to check shape of array
number of items in each dimension

- shape

In [478]:
print(a1.shape,"\n")
print(a2.shape,"\n")
print(a3.shape,"\n")

(10,) 

(3, 4) 

(2, 2, 2) 



# 3rd atribute size tells number of items in array

- size

In [479]:
print(a2.size)

12


# 4th attribute itemsize  it tells size of every item in memory
- itemsize   
- result in bytes
- int32 take 4 bytes
- int64 that is by default. always take 8 bytes 

In [480]:
print(a3.itemsize,"\n")
print(a2.itemsize)

8 

8


# 5th Attribute dtype  tells te data types of arrays

- dtype

In [481]:
print(a1.dtype,"\n")
print(a2.dtype,"\n")
print(a3.dtype)

int32 

float64 

int64


# Changing data type

## 6th attribute astype  

- astype
- best use to optimize data memory

In [482]:
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

## Array Operations 

In [483]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
print(a1,"\n")
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [484]:
# Scalar Operations / Arthmetic
multiply = print(a1 * 2,"\n") # multiply a1 each entry with  2
sub  = print(a1 - 2,"\n") # sub 2 in a1
Add = print(a1 + 2,"\n") # add 2 in a1
div = print(a1 / 2,"\n") # div a1 by 2
mod = print(a1 % 2,"\n") # a1 mod with 2
power = print(a1 ** 2,"\n") 

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]] 

[[-2 -1  0  1]
 [ 2  3  4  5]
 [ 6  7  8  9]] 

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]] 

[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]] 

[[0 1 0 1]
 [0 1 0 1]
 [0 1 0 1]] 

[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]] 



In [485]:
# reltional operation

print(a2 > 5,"\n")  #check  each membr of array is it greatr than 5 
print(a2 < 5,"\n")#check  each membr of array is it less than 5 
print(a2 != 5,"\n")#check  each membr of array is it not equal than 5 
print(a2<= 8,"\n")#check  each membr of array is it less than equal to 5 
print(a2>=4,"\n")#check  each membr of array is it greatr than equal to 5 

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]] 

[[False False False False]
 [False False False False]
 [False False False False]] 

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]] 

[[False False False False]
 [False False False False]
 [False False False False]] 

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]] 



In [486]:
# Vector Operations

# All Arthmetic operators work 
print(a1 + a2,"\n") # only possible if shape same
print(a1 - a2,"\n")
print(a1 / a2,"\n")
print(a1 * a2,"\n")
print(a1**a2,"\n")

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]] 

[[-12 -12 -12 -12]
 [-12 -12 -12 -12]
 [-12 -12 -12 -12]] 

[[0.         0.07692308 0.14285714 0.2       ]
 [0.25       0.29411765 0.33333333 0.36842105]
 [0.4        0.42857143 0.45454545 0.47826087]] 

[[  0  13  28  45]
 [ 64  85 108 133]
 [160 189 220 253]] 

[[                   0                    1                16384
              14348907]
 [          4294967296         762939453125      101559956668416
     11398895185373143]
 [ 1152921504606846976 -1261475310744950487  1864712049423024128
   6839173302027254275]] 



# Array Functions

In [487]:
a1 = np.random.random((3,3))
a1= np.round(a1*100)

a1

array([[60., 58., 41.],
       [48., 23., 94.],
       [37., 35., 12.]])

In [488]:
# max/min/sum/prod

print(np.max(a1),"\n") #give maximum from whole array
print(np.min(a1),"\n") # give minimum
print(np.sum(a1),"\n") # perform sum
print(np.prod(a1),"\n") # perform prod

94.0 

12.0 

408.0 

230097045427200.0 



In [489]:
# Accessing max from each row
# rows -> axis = 1 & col -> axis = 0 
np.max(a1,axis=1)

array([60., 94., 37.])

In [490]:
# product on columns

np.prod(a1,axis=1)

array([142680., 103776.,  15540.])

In [491]:
# mean/median/std/var

print(np.mean(a1),"\n")
print(np.median(a1),"\n")
print(np.std(a1),"\n")
print(np.var(a1),"\n")


45.333333333333336 

41.0 

22.499382707581606 

506.22222222222223 



In [492]:
# Row or column wise mean/median/std/var

print(np.mean(a1,axis=0),"\n")#column
print(np.median(a1,axis=1),"\n")#Rows
print(np.std(a1,axis=0),"\n")
print(np.var(a1,axis=1),"\n")



[48.33333333 38.66666667 49.        ] 

[58. 48. 35.] 

[ 9.39266854 14.52201394 33.950945  ] 

[ 72.66666667 864.66666667 128.66666667] 



In [493]:
# trignomatric function / Never used in ml ds

print(np.sin(a1),"\n")
print(np.cos(a1),"\n")
print(np.tan(a1),"\n")
print(np.sinc(a1),"\n")

[[-0.30481062  0.99287265 -0.15862267]
 [-0.76825466 -0.8462204  -0.24525199]
 [-0.64353813 -0.42818267 -0.53657292]] 

[[-0.95241298  0.11918014 -0.98733928]
 [-0.64014434 -0.53283302  0.96945937]
 [ 0.76541405 -0.90369221  0.84385396]] 

[[ 0.32004039  8.33085685  0.1606567 ]
 [ 1.20012724  1.58815308 -0.2529781 ]
 [-0.84077126  0.47381472 -0.63585993]] 

[[-1.14372644e-16  1.35881142e-20  1.21727856e-16]
 [-3.89817183e-17  8.81497134e-17  3.32010830e-17]
 [ 8.41782949e-18  7.12921151e-17 -3.89817183e-17]] 



In [494]:
# dot product   

a2 = np.arange(12).reshape(3,4) # dot product possible only if first matrix columns match to 2nds matrix rows in our case 3x4 =4x3  4 (columns of first)=4(rows of sec)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [495]:
# log and exponent

np.log(a1)

array([[4.09434456, 4.06044301, 3.71357207],
       [3.87120101, 3.13549422, 4.54329478],
       [3.61091791, 3.55534806, 2.48490665]])

In [496]:
np.exp(a2)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [497]:
# round / floor/ceil

np.round(np.random.random((2,3))*100)  #  roundoff to nearest int

array([[ 1., 25., 53.],
       [57., 74., 95.]])

In [498]:
np.floor(np.random.random((2,3))*100) # return to back int 

array([[93.,  1., 24.],
       [ 1.,  1.,  1.]])

In [499]:
np.ceil(np.random.random((2,3))*100) # take to next int

array([[23., 22., 20.],
       [78., 72., 83.]])

# Indexing / Slicing 

In [500]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np. arange(8).reshape(2,2,2)


In [501]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [502]:
a2


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [503]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [504]:
# indexing in 1d array  work similar as it works in python 

print(a1[0],"\n")

print(a1[5])

0 

5


In [505]:
# indexing in 2d array 

print(a2) # fetch 7 from this 

print(a2[1,3],"\n") # 1 indicate row holding 7 and 3 indicate column
print(a2[2,3]) # fetching 11

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
7 

11


In [506]:
# indexing in 3d arrays

print(a3)

print(a3[1,0,1],"\n") # fething 5 from 3d   1 indicate 2d array number which contain 5.0 indicate row of that 2d array holding 5.1 indicate column of that 2d arry holding 5 
print(a3[0,0,0]) #fetching 0

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
5 

0


# Slicning 

fetching multiple items

In [507]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [508]:
print(a1[2:5])  #slicing in 1d is same as python

[2 3 4]


In [509]:
#slicing in 2d 
a2 


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [510]:
print(a2[0,:])

[0 1 2 3]


In [511]:
print(a2[:,2])

[ 2  6 10]


In [512]:
print(a2[1:,1:3])

[[ 5  6]
 [ 9 10]]


In [513]:
print(a2[::2,::3])

[[ 0  3]
 [ 8 11]]


In [514]:
print(a2[::2,1::2])

[[ 1  3]
 [ 9 11]]


In [515]:
print(a2[1 ,::3])

[4 7]


In [516]:
print(a2[:2 ,1: ])

[[1 2 3]
 [5 6 7]]


# Slicing 3d

In [517]:
a3 = np.arange(27).reshape(3,3,3)
print(a3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [518]:
print(a3[1,:,:]) # 1 indicate number of 2d array we need / : first indicate all rows / : second indicate columns

[[ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [519]:
print(a3[::2,:,:])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [520]:
print(a3[0,1,:])

[3 4 5]


In [521]:
print(a3[1,:,1])

[10 13 16]


In [522]:
print(a3[2,1:,1:])

[[22 23]
 [25 26]]


In [523]:
print(a3[::2,0,::2])

[[ 0  2]
 [18 20]]


# Iteraing loop on numpy array

In [524]:
for i in a1:
    print(i)   # loops in 1d array return values on each iteration

0
1
2
3
4
5
6
7
8
9


In [525]:
for i in a2:  # loop on 2d array return 1 complete row on each iteration
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [526]:
for i in a3: # loops on 3d array return 1 complete 2d array  on each iteration
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


# how we cann print elements of 2d 3d array using loop using  [np.nditer(array): ] function

- np.nditer(array)

In [527]:
for i in np.nditer(a3):
    print(i)


0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [528]:
# for i in np.nditer(a2):     # element of 2d
#     print(i)

# Reshaping

- reshape
- transpose
- ravel

In [529]:
a1 = np.random.random((1,9))
print("Before reshape  \n",a1)


print("\n")
a1 = a1.reshape(3,3)  

print("After Reshape become 2d array \n",a1)

Before reshape  
 [[0.0731201  0.82578536 0.31364167 0.72007172 0.46748994 0.82226476
  0.43549646 0.41621988 0.14149945]]


After Reshape become 2d array 
 [[0.0731201  0.82578536 0.31364167]
 [0.72007172 0.46748994 0.82226476]
 [0.43549646 0.41621988 0.14149945]]


In [530]:
# transpose covert rows into columns and columns into rows

np.transpose(a1)


array([[0.0731201 , 0.72007172, 0.43549646],
       [0.82578536, 0.46748994, 0.41621988],
       [0.31364167, 0.82226476, 0.14149945]])

In [531]:
a1.T # Another syntax of taking transpose

array([[0.0731201 , 0.72007172, 0.43549646],
       [0.82578536, 0.46748994, 0.41621988],
       [0.31364167, 0.82226476, 0.14149945]])

In [532]:
# Ravel 

#It covert any dimensional array into 1d 
print("Before ravel a2 is 2d array \n" , a2)
a2 = a2.ravel()

print("\n Äfter ravel a2 become 1d \n",a2)

Before ravel a2 is 2d array 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Äfter ravel a2 become 1d 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]


# Stacking 

combine numpy arrays  of same type (shape)

In [533]:
# horizontial stacking 

a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

print(a4,"\n")

print(a5)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [534]:
np.hstack((a4,a5)) # horizontialy combine array 

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [535]:
# Vertical Stacking

np.vstack((a4,a5))  #  combine arrays Vertically

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# Spliting  breaking arrays horizontially or vertically

In [536]:
np.hsplit(a4,2) 

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [537]:
np.vsplit(a5,3) # Always cut in 3  rows

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]